### YamlMime:ManagedReference
items:
- uid: Illumination.Entities.RealObjects.ReMeshingConfig
  commentId: T:Illumination.Entities.RealObjects.ReMeshingConfig
  id: ReMeshingConfig
  parent: Illumination.Entities.RealObjects
  children:
  - Illumination.Entities.RealObjects.ReMeshingConfig.#ctor(System.Double,System.Double)
  - Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  - Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  langs:
  - csharp
  - vb
  name: ReMeshingConfig
  nameWithType: ReMeshingConfig
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig
  type: Class
  source:
    remote:
      path: Illumination/Entities/RealObjects/Mesh.cs
      branch: master
      repo: https://github.com/SharafeevRavil/lighting-calculation.git
    id: ReMeshingConfig
    path: ../Illumination/Entities/RealObjects/Mesh.cs
    startLine: 34
  assemblies:
  - Illumination
  namespace: Illumination.Entities.RealObjects
  syntax:
    content: public class ReMeshingConfig
    content.vb: Public Class ReMeshingConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  commentId: P:Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  id: MaxArea
  parent: Illumination.Entities.RealObjects.ReMeshingConfig
  langs:
  - csharp
  - vb
  name: MaxArea
  nameWithType: ReMeshingConfig.MaxArea
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  type: Property
  source:
    remote:
      path: Illumination/Entities/RealObjects/Mesh.cs
      branch: master
      repo: https://github.com/SharafeevRavil/lighting-calculation.git
    id: MaxArea
    path: ../Illumination/Entities/RealObjects/Mesh.cs
    startLine: 36
  assemblies:
  - Illumination
  namespace: Illumination.Entities.RealObjects
  syntax:
    content: public double MaxArea { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property MaxArea As Double
  overload: Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea*
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  commentId: P:Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  id: MaxEdgeLength
  parent: Illumination.Entities.RealObjects.ReMeshingConfig
  langs:
  - csharp
  - vb
  name: MaxEdgeLength
  nameWithType: ReMeshingConfig.MaxEdgeLength
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  type: Property
  source:
    remote:
      path: Illumination/Entities/RealObjects/Mesh.cs
      branch: master
      repo: https://github.com/SharafeevRavil/lighting-calculation.git
    id: MaxEdgeLength
    path: ../Illumination/Entities/RealObjects/Mesh.cs
    startLine: 37
  assemblies:
  - Illumination
  namespace: Illumination.Entities.RealObjects
  syntax:
    content: public double MaxEdgeLength { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property MaxEdgeLength As Double
  overload: Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength*
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.#ctor(System.Double,System.Double)
  commentId: M:Illumination.Entities.RealObjects.ReMeshingConfig.#ctor(System.Double,System.Double)
  id: '#ctor(System.Double,System.Double)'
  parent: Illumination.Entities.RealObjects.ReMeshingConfig
  langs:
  - csharp
  - vb
  name: ReMeshingConfig(double, double)
  nameWithType: ReMeshingConfig.ReMeshingConfig(double, double)
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.ReMeshingConfig(double, double)
  type: Constructor
  source:
    remote:
      path: Illumination/Entities/RealObjects/Mesh.cs
      branch: master
      repo: https://github.com/SharafeevRavil/lighting-calculation.git
    id: .ctor
    path: ../Illumination/Entities/RealObjects/Mesh.cs
    startLine: 39
  assemblies:
  - Illumination
  namespace: Illumination.Entities.RealObjects
  syntax:
    content: public ReMeshingConfig(double maxArea, double maxEdgeLength)
    parameters:
    - id: maxArea
      type: System.Double
    - id: maxEdgeLength
      type: System.Double
    content.vb: Public Sub New(maxArea As Double, maxEdgeLength As Double)
  overload: Illumination.Entities.RealObjects.ReMeshingConfig.#ctor*
  nameWithType.vb: ReMeshingConfig.New(Double, Double)
  fullName.vb: Illumination.Entities.RealObjects.ReMeshingConfig.New(Double, Double)
  name.vb: New(Double, Double)
references:
- uid: Illumination.Entities.RealObjects
  commentId: N:Illumination.Entities.RealObjects
  href: Illumination.html
  name: Illumination.Entities.RealObjects
  nameWithType: Illumination.Entities.RealObjects
  fullName: Illumination.Entities.RealObjects
  spec.csharp:
  - uid: Illumination
    name: Illumination
    href: Illumination.html
  - name: .
  - uid: Illumination.Entities
    name: Entities
    href: Illumination.Entities.html
  - name: .
  - uid: Illumination.Entities.RealObjects
    name: RealObjects
    href: Illumination.Entities.RealObjects.html
  spec.vb:
  - uid: Illumination
    name: Illumination
    href: Illumination.html
  - name: .
  - uid: Illumination.Entities
    name: Entities
    href: Illumination.Entities.html
  - name: .
  - uid: Illumination.Entities.RealObjects
    name: RealObjects
    href: Illumination.Entities.RealObjects.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea*
  commentId: Overload:Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  href: Illumination.Entities.RealObjects.ReMeshingConfig.html#Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
  name: MaxArea
  nameWithType: ReMeshingConfig.MaxArea
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.MaxArea
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength*
  commentId: Overload:Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  href: Illumination.Entities.RealObjects.ReMeshingConfig.html#Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
  name: MaxEdgeLength
  nameWithType: ReMeshingConfig.MaxEdgeLength
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.MaxEdgeLength
- uid: Illumination.Entities.RealObjects.ReMeshingConfig.#ctor*
  commentId: Overload:Illumination.Entities.RealObjects.ReMeshingConfig.#ctor
  href: Illumination.Entities.RealObjects.ReMeshingConfig.html#Illumination.Entities.RealObjects.ReMeshingConfig.#ctor(System.Double,System.Double)
  name: ReMeshingConfig
  nameWithType: ReMeshingConfig.ReMeshingConfig
  fullName: Illumination.Entities.RealObjects.ReMeshingConfig.ReMeshingConfig
  nameWithType.vb: ReMeshingConfig.New
  fullName.vb: Illumination.Entities.RealObjects.ReMeshingConfig.New
  name.vb: New
